version: "3.7"

services:
# image for hosting the frontend (wordpress)
  wordpress:
    image: wordpress:latest
    container_name: frontend
    ports:
      - 8085:80
      - 443:443
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress_jeffrey
      WORDPRESS_DB_PASSWORD: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress_db
    secrets:
      - db_password
    volumes:
      - ./src:/var/www/html
    healthcheck: 
      test: [ "CMD", "curl", "--fail", "http://localhost" ]
      interval: "30s"
      timeout: "5s"
      retries: 3

# image for the mysql database
  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_jeffrey
      MYSQL_PASSWORD: /run/secrets/db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    secrets:
      - db_password
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d

# initialise secret for mysql password
secrets:
  db_password:
    file: db_password.txt

volumes:
  wordpress:
  mysql: