version: "3.1"

services:
  wordpress:
    image: wordpress
    ports:
      - 8085:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress_jeffrey
      WORDPRESS_DB_PASSWORD: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress_db
    secrets:
      - db_password
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_jeffrey
      MYSQL_RANDOM_PASSWORD: '1'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    secrets:
      - db_password
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d

secrets:
  db_password:
    file: db_password.txt

volumes:
  wordpress:
  mysql: