name: Deployment - terraform apply

on:
  workflow_dispatch:
    inputs:
        action_type:
            description: "Type of action you want to take (i.e. 'build' or 'destroy')"
            required: true

env:
   AWS_REGION: ap-southeast-2
   IAM_ROLE: "arn:aws:iam::663790350014:role/GithubActions-basic-wordpress-deployment"
   TF_VERSION: 1.3.7
permissions: 
   id-token: write
   contents: read

jobs:
  tf-wordpress-deploy-first-time:
    name: 'tf-wordpress-deploy'
    runs-on: ubuntu-latest
    if: inputs.action_type == 'build'
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

        # Create the key pair for the first time
        # Comment out this step if you're running this job after the first time
      - name: Create Key Pair
        run: aws ec2 create-key-pair \
          --key-name wp-key \
          --output text > wp-key.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: false
  
  tf-wordpress-destroy:
    name: 'tf-wordpress-destroy'
    runs-on: ubuntu-latest
    if: inputs.action_type == 'destroy'
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete Key Pair
        run: aws ec2 delete-key-pair --key-name wp-key

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
      
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        continue-on-error: false

